name: Codacy Coverage Report

on:
  push:
    branches: [ "dev" ]
  schedule:
    - cron: '32 5 * * 0'

permissions:
  contents: read

jobs:
  build-coverage:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout Code
       uses: actions/checkout@v2

     - name: Install composer and dependencies
       uses: php-actions/composer@v6

     - name: Execute tests (Unit and Feature tests) via PestPHP
       env:
           XDEBUG_MODE: coverage
       run: ./vendor/bin/pest --coverage-clover ./clover.xml
         
     - name: Codacy Coverage Reporter
       uses: codacy/codacy-coverage-reporter-action@v1.3.0
       with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./clover.xml
